### ISSUE TITLE
Problem of generate my own EmojiConfig

### ISSUE THREAD

**Issue by andyleekp** [xiaobin83/Unity3D.EmojiText#2]
Hi, thanks for the excellent unity emoji plugin!
I'm trying to generate my own EmojiConfig from my own Sprite Texture. 
However in Emoji-->Atlas Baker, 
there is a warning about "Please provide path to textures to atlas". 
What is the meaning of "path to textures to atlas" and what should I do? Thanks a lot!

**Comment by xiaobin83** [comment]
just paste the path to your own emoji textures. the name of texture is the Unicode of emoji character.
for example, you can paste path 'path_to/Unity3D.EmojiText/Assets/TwitterEmoji' to generate config for TwitterEmoji.

**Comment by xiaobin83** [comment]
plz check README at 9b7f690
